apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rabbitmq-ingress
  namespace: {{ .Values.namespace | quote  }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`rabbitmq.localhost`)
      services:
        - name: "{{ .Values.rabbitmq.serviceName }}-service"
          port: {{ .Values.rabbitmq.managementPort }}
