apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Values.focus.name }}-ingress"
  namespace: {{ .Values.namespace | quote  }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`focus.localhost`)
      services:
        - name: "{{ .Values.focus.name }}-service"
          port: {{ .Values.focus.service.port }}
