apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.focus_postgres.serviceName | replace "_" "-" | lower }}"
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.focus_postgres.port }}
      targetPort: {{ .Values.focus_postgres.port }}
      name: postgres
