apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  namespace: focus
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
