apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.focus.postgres.serviceName }}"
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: focus-postgres
  ports:
    - port: {{ .Values.focus.postgres.port }}
      targetPort: {{ .Values.focus.postgres.port }}
      name: postgres
