apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.focus_postgres.persistence.claimName }}
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.focus_postgres.persistence.storageClassName | default "ebs-sc" }}
  resources:
    requests:
      storage: {{ .Values.focus_postgres.persistence.size | default "1Gi" }}