apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.focus_secrets.name | replace "_" "-" | lower }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.focus_secrets.values.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.focus_secrets.values.DB_PASSWORD | quote }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.focus_secrets.values.QUARKUS_DATASOURCE_USERNAME | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.focus_secrets.values.QUARKUS_DATASOURCE_PASSWORD | quote }}
