apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.focus.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.focus.secrets.values.QUARKUS_DATASOURCE_USERNAME | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.focus.secrets.values.QUARKUS_DATASOURCE_PASSWORD | quote }}