{{- if .Values.focus.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.focus.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  {{- with .Values.focus.secrets.values }}
  QUARKUS_DATASOURCE_USERNAME: {{ .QUARKUS_DATASOURCE_USERNAME | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .QUARKUS_DATASOURCE_PASSWORD | quote }}
  {{- end }}
{{- end }}
