{{- if and .Values.ingress.tls.create .Values.ingress.tls.secretName .Values.ingress.tls.crt .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | quote }}
  namespace: {{ .Values.namespace | quote }}
type: kubernetes.io/tls
stringData:
  tls.crt: |-
{{ .Values.ingress.tls.crt | nindent 4 }}
  tls.key: |-
{{ .Values.ingress.tls.key | nindent 4 }}
{{- if and .Values.ingress.tls.createInFrontend (ne .Values.frontend.namespace .Values.namespace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | quote }}
  namespace: {{ .Values.frontend.namespace | quote }}
type: kubernetes.io/tls
stringData:
  tls.crt: |-
{{ .Values.ingress.tls.crt | nindent 4 }}
  tls.key: |-
{{ .Values.ingress.tls.key | nindent 4 }}
{{- end }}
{{- end }}
