{{- if .Values.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Values.namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerconfigjson | b64enc }}
{{- end }}
