services:
  auth_database:
    container_name: auth-postgres-prod
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME?missing db name}
      POSTGRES_USER: ${DB_USERNAME?missing db username}
      POSTGRES_PASSWORD: ${DB_PASSWORD?missing db password}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - default_network
  
  auth_app:
    container_name: auth-app-prod
    image: 758280076486.dkr.ecr.eu-central-1.amazonaws.com/focusboard/auth:latest
    environment:
      DB_HOST: auth_database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME?missing db name}
      DB_USERNAME: ${DB_USERNAME?missing db username}
      DB_PASSWORD: ${DB_PASSWORD?missing db password}
      JWT_SECRET: ${JWT_SECRET?missing jwt secret}
      PEPPER: ${PEPPER?missing pepper}
      PORT: ${PORT?missing app port}
      GRPC_PORT: ${GRPC_PORT?missing grpc port}
    depends_on:
      - auth_database
    networks:
      - default_network

  focus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      QUARKUS_PROFILE: docker
    restart: unless-stopped
    networks:
      - default_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: focus
      POSTGRES_USER: focus
      POSTGRES_PASSWORD: focus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focus -d focus"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default_network

volumes:
  auth_db_data:
  postgres_data:

networks:
  default_network:
    driver: bridge