apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth_secrets.name | replace "_" "-" | lower }}
  namespace: {{ .Values.namespace | quote  }}
type: Opaque
data:
  # Database configuration
  DB_USERNAME: {{ .Values.auth_secrets.values.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.auth_secrets.values.DB_PASSWORD | quote }}

  # Application configuration
  JWT_SECRET: {{ .Values.auth_secrets.values.JWT_SECRET | quote }}
  PEPPER: {{ .Values.auth_secrets.values.PEPPER | quote }}

  # RabbitMQ configuration
  RABBITMQ_USER: {{ .Values.auth_secrets.values.RABBITMQ_USER | quote }}
  RABBITMQ_PASSWORD: {{ .Values.auth_secrets.values.RABBITMQ_PASSWORD | quote }}

  # Email configuration
  SMTP_USER: {{ .Values.auth_secrets.values.SMTP_USER | quote }}
  SMTP_PASS: {{ .Values.auth_secrets.values.SMTP_PASS | quote }}
  SMTP_HOST: {{ .Values.auth_secrets.values.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.auth_secrets.values.SMTP_PORT | quote }}
  SMTP_FROM: {{ .Values.auth_secrets.values.SMTP_FROM | quote }}
