apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.auth.name }}-service"
  namespace: {{ .Values.namespace | quote  }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.auth.name }}
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
      name: http
    - port: {{ .Values.auth.grpcPort }}
      targetPort: {{ .Values.auth.grpcPort }}
      name: grpc

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.postgres.serviceName }}"
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.rabbitmq.serviceName }}"
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: rabbitmq
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
      name: amqp
    - port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
      name: management
