apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: {{ .Values.postgres.serviceName }}

  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.persistence.claimName }}

      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        ports:
        - containerPort: {{ .Values.postgres.port }}
          name: postgres
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: {{ .Values.postgres.configmap.name }}
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: DB_USERNAME

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: {{ .Values.rabbitmq.serviceName }}

  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.rabbitmq.persistence.claimName }}
      containers:

      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
        ports:
        - containerPort: {{ .Values.rabbitmq.port }}
          name: amqp
        - containerPort: {{ .Values.rabbitmq.managementPort }}
          name: management
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: RABBITMQ_PASSWORD
