apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.frontend.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}

    spec:
      initContainers:
        - name: frontend-wait-for-dependencies
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - >
              echo "Waiting for Auth service...";
              until nc -z -w 2 {{ .Values.auth.name }}-service.{{ .Values.namespace }}.svc.cluster.local {{ .Values.auth.port }}; do
                sleep 2;
              done;
              echo "Waiting for Focus service...";
              until nc -z -w 2 {{ .Values.focus.name }}-service.{{ .Values.namespace }}.svc.cluster.local {{ .Values.focus.service.port }}; do
                sleep 2;
              done;
              echo "Dependencies are ready!";

      imagePullSecrets:
        - name: {{ .Values.pullSecret.name }}

      containers:
       - name: {{ .Values.frontend.name }}
         image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
         ports:
          - containerPort: {{ .Values.frontend.port }}
            name: http
            protocol: TCP
         envFrom:
         - configMapRef:
             name: app-config
