apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespace | quote  }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`frontend.localhost`)
      services:
        - name: "{{ .Values.frontend.name }}-service"
          port: {{ .Values.frontend.port }}
