apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth-ingress
  namespace: {{ .Values.namespace | quote  }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.auth.host }}`)
      services:
        - name: "{{ .Values.auth.name }}-service"
          port: {{ .Values.auth.port }}
  {{ if or .Values.ingress.tls.secretName .Values.ingress.tls.certResolver }}
  tls:
    {{ if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName | quote }}
    {{ end }}
    {{ if .Values.ingress.tls.certResolver }}
    certResolver: {{ .Values.ingress.tls.certResolver | quote }}
    {{ end }}
  {{ end }}
