apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.persistence.claimName }}
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rabbitmq.persistence.claimName }}
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
