apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.auth.name }}-service"
  namespace: {{ .Values.namespace | quote  }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.auth.name }}
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
      name: http
    - port: {{ .Values.auth.grpcPort }}
      targetPort: {{ .Values.auth.grpcPort }}
      name: grpc

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.auth.postgres.serviceName }}"
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: auth-postgres
  ports:
    - port: {{ .Values.auth.postgres.port }}
      targetPort: {{ .Values.auth.postgres.port }}
      name: postgres
