apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-postgres-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: {{ .Values.auth_postgres.serviceName | replace "_" "-" | lower }}

  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.auth_postgres.persistence.claimName }}

      containers:
      - name: postgres
        image: "{{ .Values.auth_postgres.image.repository }}:{{ .Values.auth_postgres.image.tag }}"
        ports:
        - containerPort: {{ .Values.auth_postgres.port }}
          name: postgres
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: {{ .Values.auth_postgres.configmap.name }}
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth_secrets.name | replace "_" "-" | lower }}
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth_secrets.name | replace "_" "-" | lower }}
              key: DB_USERNAME
