apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.analytics.configmap.name }}
  namespace: {{ .Values.namespace | quote }}
data:
  PORT: {{ .Values.analytics.port | quote }}
  GRPC_PORT: {{ .Values.analytics.grpcPort | quote }}
  KAFKA_BROKERS: {{ .Values.analytics.env.KAFKA_BROKERS | quote }}
  KAFKA_TOPIC: {{ .Values.analytics.env.KAFKA_TOPIC | quote }}
  KAFKA_GROUP_ID: {{ .Values.analytics.env.KAFKA_GROUP_ID | quote }}
  STORE_BACKEND: {{ .Values.analytics.env.STORE_BACKEND | quote }}
  CONFIG_PATH: {{ .Values.analytics.env.CONFIG_PATH | quote }}
  POSTGRES_HOST: {{ .Values.analytics_postgres.serviceName | quote }}
  POSTGRES_PORT: {{ .Values.analytics_postgres.port | quote }}
  POSTGRES_DB: {{ .Values.analytics_postgres.database | quote }}
