apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.analytics.name }}
spec:
  replicas: {{ .Values.analytics.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.analytics.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.analytics.name }}
    spec:
      initContainers:
        - name: analytics-wait-for-dependencies
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - >
              echo "Waiting for Analytics PostgreSQL...";
              until nc -z -w 2 {{ .Values.analytics.postgres.serviceName }}.{{ .Values.namespace }}.svc.cluster.local {{ .Values.analytics.postgres.port }}; do
                sleep 2;
              done;
              echo "Waiting for Redpanda Kafka...";
              until nc -z -w 2 redpanda.{{ .Values.namespace }}.svc.cluster.local 9092; do
                sleep 2;
              done;
              echo "Dependencies are ready!";

      imagePullSecrets:
        - name: {{ .Values.pullSecret.name }}
      containers:
        - name: {{ .Values.analytics.name }}
          image: "{{ .Values.analytics.image.repository }}:{{ .Values.analytics.image.tag }}"
          ports:
            - containerPort: {{ .Values.analytics.port }}
              name: http
              protocol: TCP
            - containerPort: {{ .Values.analytics.grpcPort }}
              name: grpc
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.analytics.port }}
            initialDelaySeconds: {{ .Values.analytics.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.analytics.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.analytics.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.analytics.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.analytics.port }}
            initialDelaySeconds: {{ .Values.analytics.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.analytics.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.analytics.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.analytics.probes.readiness.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.analytics.resources.requests.cpu }}
              memory: {{ .Values.analytics.resources.requests.memory }}
            limits:
              cpu: {{ .Values.analytics.resources.limits.cpu }}
              memory: {{ .Values.analytics.resources.limits.memory }}
          envFrom:
            - configMapRef:
                name: {{ .Values.analytics.configmap.name }}
            - secretRef:
                name: {{ .Values.analytics.secrets.name }}
