apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: analytics-ingress
  namespace: {{ .Values.namespace | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`analytics.localhost`)
      services:
        - name: "{{ .Values.analytics.name }}-service"
          port: {{ .Values.analytics.port }}
