apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.analytics.postgres.serviceName | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: analytics-postgres
  ports:
    - port: {{ .Values.analytics.postgres.port }}
      targetPort: {{ .Values.analytics.postgres.port }}
      name: postgres