apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-postgres-config
  namespace: {{ .Values.namespace | quote }}
data:
  POSTGRES_DB: {{ .Values.analytics.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.analytics.postgres.user | quote }}