apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: analytics-postgres
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: {{ .Values.analytics.postgres.serviceName | quote }}

  replicas: 1
  selector:
    matchLabels:
      app: analytics-postgres

  template:
    metadata:
      labels:
        app: analytics-postgres
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.analytics.postgres.persistence.claimName }}

      containers:
      - name: postgres
        image: "{{ .Values.analytics.postgres.image.repository }}:{{ .Values.analytics.postgres.image.tag }}"
        ports:
        - containerPort: {{ .Values.analytics.postgres.port }}
          name: postgres
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: analytics-postgres-config
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          value: {{ .Values.analytics.postgres.user | quote }}