{{- if .Values.analytics.secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.analytics.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  {{- with .Values.analytics.secrets.values }}
  POSTGRES_DSN: {{ .POSTGRES_DSN | quote }}
  {{- end }}
{{- end }}
