{{- if .Values.analytics_secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.analytics_secrets.name | replace "_" "-" | lower }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  {{- with .Values.analytics_secrets.values }}
  POSTGRES_DSN: {{ .POSTGRES_DSN | quote }}
  {{- end }}
{{- end }}
