apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.analytics_secrets.name | replace "_" "-" | lower }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  POSTGRES_DSN: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=disable" .Values.analytics_postgres.user .Values.analytics_postgres.user .Values.analytics_postgres.serviceName (int .Values.analytics_postgres.port) .Values.analytics_postgres.database | quote }}
