apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.email.configmap.name }}
  namespace: {{ .Values.namespace | quote }}
data:
  RABBITMQ_HOST: "{{ .Values.rabbitmq.serviceName }}.{{ .Values.namespace }}.svc.cluster.local"
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}

  SMTP_HOST: {{ .Values.email.smtp.host | quote }}
  SMTP_PORT: {{ .Values.email.smtp.port | quote }}
  SMTP_FROM: {{ .Values.email.smtp.from | quote }}
