enabled: true
image:
  repository: docker.redpanda.com/redpandadata/redpanda
  tag: v25.1.2
replicaCount: 1
persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
service:
  type: ClusterIP
  port: 9092
  outsidePort: 19092
  adminPort: 9644
configMap:
  name: redpanda-config
config:
  config_file: /etc/redpanda/redpanda.yaml
  redpanda:
    data_directory: /var/lib/redpanda/data
    node_id: 0
    empty_seed_starts_cluster: true
    developer_mode: true
    seed_servers: []
    rpc_server:
      address: 0.0.0.0
      port: 33145
    advertised_rpc_api:
      address: redpanda
      port: 33145
    admin:
      - address: 0.0.0.0
        port: 9644
        name: admin
    kafka_api:
      - address: 0.0.0.0
        port: 9092
        name: kafka
        authentication_method: none
    advertised_kafka_api:
      - address: redpanda
        port: 9092
        name: kafka
  pandaproxy:
    pandaproxy_api:
      - address: 0.0.0.0
        port: 8082
        name: proxy
    advertised_pandaproxy_api:
      - address: redpanda
        port: 8082
        name: proxy
topicInit:
  enabled: true
  name: focus.events
  partitions: 3
  replicas: 1