apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: outside
      port: {{ .Values.service.outsidePort }}
      targetPort: {{ .Values.service.outsidePort }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.service.adminPort }}

---
# headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: redpanda-headless
  labels:
    app: redpanda
spec:
  clusterIP: None
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}