apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  serviceName: redpanda-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redpanda
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      initContainers:
      - name: copy-redpanda-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
          - /bin/sh
          - -c
          - cp /config-source/redpanda.yaml /etc/redpanda/redpanda.yaml
        volumeMounts:
        - name: config-source
          mountPath: /config-source
          readOnly: true
        - name: redpanda-config
          mountPath: /etc/redpanda
      containers:
      - name: redpanda
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
          - /opt/redpanda/bin/redpanda
        args:
          - --redpanda-cfg
          - /etc/redpanda/redpanda.yaml
          - --smp=1
          - --memory=1G
          - --reserve-memory=0M
          - --overprovisioned
        ports:
        - name: kafka
          containerPort: {{ .Values.service.port }}
        - name: outside
          containerPort: {{ .Values.service.outsidePort }}
        - name: admin
          containerPort: {{ .Values.service.adminPort }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        - name: redpanda-config
          mountPath: /etc/redpanda
      volumes:
      - name: config-source
        configMap:
          name: {{ .Values.configMap.name }}
      - name: redpanda-config
        emptyDir: {}
